server:
   port: 9999
   contextPath: /api

logging:
   level:
      com:
         gruposantander:
            subscriberSarq: DEBUG
      org:
         hibernate: INFO

spring:
   profiles:
      active: test
   application:
      name: subscriberSarq
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      platform: h2
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
   jpa:
      show-sql: true
   cloud:
      stream:
         kafka:
            binder:
               brokers:
                  localhost:9092
         bindings:
            subscribe:
               destination: custodian
               contentType: application/json